name=('deepak', 'sharma','shail','aman')
name2=list(name)
name2.append(200)
print(name2)
name2.remove(200)
print(name2)
name2.insert(2,4)
print(name2)
name2.pop(1)
print(name2)
name=list(name2)
print("this is tuple",name)